services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: m3_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backend_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - backend_network
    restart: unless-stopped

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: m3_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    networks:
      - backend_network
    restart: unless-stopped

  # Node.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: m3_backend_api
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: backend_db
      QDRANT_URL: http://qdrant:6333
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      qdrant:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend_network
    restart: unless-stopped

volumes:
  mysql_data:
  qdrant_storage:

networks:
  backend_network:
    driver: bridge
